---
- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify:
    - Restart nginx

- name: Make nginx-conf.d directory
  ansible.builtin.file:
    path: /etc/nginx/nginx-conf.d/
    state: directory
    mode: 0755
  when: nginx_additional_conf_files is defined

- name: Copy additional nginx configuration files
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "/etc/nginx/nginx-conf.d/{{ item.key }}"
    mode: 0644
  loop: "{{ nginx_additional_conf_files | dict2items }}"
  when: nginx_additional_conf_files is defined
  notify:
    - Restart nginx

- name: Copy nginx server configuration files
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "/etc/nginx/conf.d/{{ item.key }}"
    mode: 0644
  loop: "{{ nginx_server_conf_files | dict2items }}"
  when: nginx_server_conf_files is defined
  notify:
    - Restart nginx

- name: Copy nginx sites-enabled configuration files
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}"
    mode: 0644
  loop: "{{ nginx_server_sites_enabled | dict2items }}"
  when: nginx_server_sites_enabled is defined
  notify: 
    - Restart nginx
      
- name: Copy certificates
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "/etc/nginx/{{ item.key }}"
    mode: 0644
  when: nginx_certificate_files is defined
  loop: "{{ nginx_certificate_files | dict2items }}"
  notify:
    - Restart nginx

- name: Copy keys
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "/etc/nginx/{{ item.key }}"
    mode: 0600
  when: nginx_key_files is defined
  loop: "{{ nginx_key_files | dict2items }}"
  notify:
    - Restart nginx