---
- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify:
    - Restart nginx

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
